### ISSUE TITLE
RuntimeError, ''cnn_runner.py'' doesn't work, any clue?

### ISSUE THREAD

**Issue by XYAskWhy** [skrypka/imaterialist-furniture-2018#1]
Traceback (most recent call last):
  File "cnn_runner.py", line 157, in <module>
    train()
  File "cnn_runner.py", line 111, in train
    for inputs, labels in pbar:
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 941, in __iter__
    for obj in iterable:
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 135, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 135, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 112, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/home/rs/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 at /opt/conda/conda-bld/pytorch_1523244252089/work/torch/lib/TH/generic/THTensorMath.c:2897

I am using a conda environment of python 3.6 with pytorch0.3, tried pytorch0.2, doesn't work either.

**Comment by roman-dowakin** [comment]
Maybe I uploaded buggy version of function `safe_stack_2array` in `utils.py`. This is my current version and it should work:
```python
def safe_stack_2array(acc, a):
    a = a.unsqueeze(-1)
    if acc is None:
        return a
    return torch.cat((acc, a), dim=acc.dim() - 1)
```

**Comment by XYAskWhy** [comment]
@roman-dowakin , thanks for your quick reply. But replacing this block of code doesn't help, same error still occurs. By the way, I check all the functions, but it seems that the ''safe_stack_2array'' function is never used.  Is this the problem? Since it's a safe checking function and the error do occur during randomly during the early stage of training steps. If so, where should I use it? New to PyTorch, many thanks.

**Comment by ShusenTang** [comment]
I have this problem only in the 'predict' mode,  this is my [solution](https://www.kaggle.com/c/imaterialist-challenge-furniture-2018/discussion/56051), give me a upvote if it's useful😄

**Comment by roman-dowakin** [comment]
Sorry for long response. I'm not sure what the bug and how to fix it. My current code is so different right now, so it's not easy to use old code (. Sorry.

I'd suggest to just print input.size() or other tensors and see their sizes.

I don't have problem as @ShusenTang you have. In `download.py` I converted all images to 3 channels.

Also, after the end of competition I'm going to update this repo with the final version without any bugs.

**Comment by XYAskWhy** [comment]
Thanks @roman-dowakin, the problem is indeed the datasets have 2/4 channel pictures in it. I didn't use your downloader.py and didn't convert all images to 3 channels.
Thanks @ShusenTang, and for the predict mode problem, the code should be changed to:
``
